version: '3.8'

services:
  pokeapi:
    build: .
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: 'postgresql+psycopg2://poke:pokepass@db/pokeapi'
    restart: always

  db:
    environment:
      POSTGRES_USER: poke
      POSTGRES_PASSWORD: pokepass
      POSTGRES_DB: pokeapi
    image: postgres:9.6
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
    pg-data:
